-- MySQL Script generated by MySQL Workbench
-- Tue Jan  5 19:21:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiendatarjetas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendatarjetas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendatarjetas` DEFAULT CHARACTER SET utf8 ;
USE `tiendatarjetas` ;

-- -----------------------------------------------------
-- Table `tiendatarjetas`.`tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendatarjetas`.`tarjeta` (
  `idtarjeta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  `fecha_publicacion` DATE NULL,
  `imagen` VARCHAR(150) NULL,
  PRIMARY KEY (`idtarjeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendatarjetas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendatarjetas`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendatarjetas`.`usuariotarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendatarjetas`.`usuariotarjeta` (
  `idusuario` INT NOT NULL,
  `idtarjeta` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `idtarjeta`),
  INDEX `idtarjeta_idx` (`idtarjeta` ASC) VISIBLE,
  CONSTRAINT `idusuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `tiendatarjetas`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idtarjeta`
    FOREIGN KEY (`idtarjeta`)
    REFERENCES `tiendatarjetas`.`tarjeta` (`idtarjeta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
